/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libSpartanScytale_JavaSpartanScytale */

#ifndef _Included_libSpartanScytale_JavaSpartanScytale
#define _Included_libSpartanScytale_JavaSpartanScytale
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libSpartanScytale_JavaSpartanScytale
 * Method:    codificar
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_libSpartanScytale_JavaSpartanScytale_codificar
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     libSpartanScytale_JavaSpartanScytale
 * Method:    decodificar
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_libSpartanScytale_JavaSpartanScytale_decodificar
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
